import json
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent.parent
notebook_path = repo_root / "AI_Chatbot_for_Mentsl_health-" / "AI_Mental_Health.ipynb"

cells = []

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Notebook environment check\n",
        "import sys, importlib.util\n",
        "print('Python:', sys.executable)\n",
        "for pkg in ['pandas','numpy','matplotlib','seaborn','nltk','streamlit','sklearn']:\n",
        "    print(f'{pkg}:', 'OK' if importlib.util.find_spec(pkg) else 'MISSING')\n",
    ],
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Imports and NLTK setup\n",
        "import re\n",
        "from pathlib import Path\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import nltk\n",
        "from nltk.corpus import stopwords\n",
        "from nltk.tokenize import word_tokenize\n",
        "from sklearn.feature_extraction.text import TfidfVectorizer\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.preprocessing import LabelEncoder\n",
        "from sklearn.svm import LinearSVC\n",
        "from sklearn.metrics import accuracy_score, classification_report\n",
        "\n",
        "def ensure_nltk_resource(resource_path, package_name):\n",
        "    try:\n",
        "        nltk.data.find(resource_path)\n",
        "    except LookupError:\n",
        "        nltk.download(package_name, quiet=True)\n",
        "\n",
        "ensure_nltk_resource('corpora/stopwords', 'stopwords')\n",
        "ensure_nltk_resource('tokenizers/punkt', 'punkt')\n",
        "ensure_nltk_resource('tokenizers/punkt_tab/english', 'punkt_tab')\n",
    ],
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Data loading with robust path resolution\n",
        "def find_project_root():\n",
        "    candidates = [\n",
        "        Path.cwd(),\n",
        "        Path.cwd() / 'AI_Chatbot_for_Mentsl_health-',\n",
        "        Path.cwd().parent,\n",
        "        Path.cwd().parent / 'AI_Chatbot_for_Mentsl_health-',\n",
        "    ]\n",
        "    for candidate in candidates:\n",
        "        if (candidate / 'app.py').exists() or (candidate / 'AI_Mental_Health.ipynb').exists():\n",
        "            return candidate.resolve()\n",
        "    return Path.cwd().resolve()\n",
        "\n",
        "PROJECT_ROOT = find_project_root()\n",
        "ARCHIVE_DATA_PATHS = [\n",
        "    PROJECT_ROOT / 'archive' / 'mental_health_comprehensive.csv',\n",
        "    PROJECT_ROOT / 'AI_Chatbot_for_Mentsl_health-' / 'archive' / 'mental_health_comprehensive.csv',\n",
        "]\n",
        "FALLBACK_DATA_PATHS = [\n",
        "    PROJECT_ROOT / 'mental_health_data.csv',\n",
        "    PROJECT_ROOT / 'AI_Chatbot_for_Mentsl_health-' / 'mental_health_data.csv',\n",
        "]\n",
        "\n",
        "def build_fallback_dataframe():\n",
        "    return pd.DataFrame([\n",
        "        {'text': 'I feel anxious and my chest feels tight.', 'intent': 'Panic/Anxiety'},\n",
        "        {'text': 'I have been feeling down and hopeless for days.', 'intent': 'Depression/Mood'},\n",
        "        {'text': 'I need help finding a therapist or counselor.', 'intent': 'Treatment/Help'},\n",
        "        {'text': 'Can you explain what bipolar disorder is?', 'intent': 'Mental Illness Info'},\n",
        "        {'text': 'I had a panic attack after a stressful event.', 'intent': 'Stress/Trauma'},\n",
        "        {'text': 'I cannot sleep well at night and feel tired.', 'intent': 'Sleep'},\n",
        "    ])\n",
        "\n",
        "dataset_source = None\n",
        "for archive_path in ARCHIVE_DATA_PATHS:\n",
        "    if archive_path.exists():\n",
        "        data = pd.read_csv(archive_path, usecols=['text', 'class'], low_memory=False).dropna(subset=['text', 'class'])\n",
        "        data = data.rename(columns={'class': 'intent'})\n",
        "        dataset_source = archive_path\n",
        "        break\n",
        "else:\n",
        "    for fallback_path in FALLBACK_DATA_PATHS:\n",
        "        if fallback_path.exists():\n",
        "            data = pd.read_csv(fallback_path)\n",
        "            if 'intent' not in data.columns and 'class' in data.columns:\n",
        "                data = data.rename(columns={'class': 'intent'})\n",
        "            dataset_source = fallback_path\n",
        "            break\n",
        "    else:\n",
        "        data = build_fallback_dataframe()\n",
        "        dataset_source = 'built-in fallback dataset'\n",
        "\n",
        "df = data.dropna(subset=['text', 'intent']).copy()\n",
        "df['intent'] = df['intent'].astype(str)\n",
        "print('Dataset source:', dataset_source)\n",
        "print(df.head())\n",
    ],
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Cleaner preprocessing\n",
        "stop_words = set(stopwords.words('english'))\n",
        "\n",
        "def clean_text(text, stop_words=None):\n",
        "    if stop_words is None:\n",
        "        stop_words = set(stopwords.words('english'))\n",
        "\n",
        "    text = str(text).lower()\n",
        "    text = re.sub(r'http\\S+|www\\.\\S+', ' ', text)\n",
        "    text = re.sub(r'[^a-z0-9\\s]', ' ', text)\n",
        "    text = re.sub(r'\\s+', ' ', text).strip()\n",
        "    tokens = word_tokenize(text, preserve_line=True)\n",
        "    tokens = [word for word in tokens if word.isalnum() and word not in stop_words]\n",
        "    return ' '.join(tokens)\n",
        "\n",
        "df['clean_text'] = df['text'].fillna('').apply(clean_text)\n",
        "print(df[['text', 'clean_text']].head())\n",
    ],
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Train the intent classifier\n",
        "vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1, 2), min_df=2, sublinear_tf=True)\n",
        "X = vectorizer.fit_transform(df['clean_text'])\n",
        "encoder = LabelEncoder()\n",
        "y = encoder.fit_transform(df['intent'])\n",
        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
        "model = LinearSVC(class_weight='balanced', random_state=42)\n",
        "model.fit(X_train, y_train)\n",
        "pred = model.predict(X_test)\n",
        "print('Accuracy:', round(accuracy_score(y_test, pred), 4))\n",
        "print(classification_report(y_test, pred, target_names=encoder.classes_, zero_division=0))\n",
    ],
})

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Prediction helper\n",
        "def predict_intent(user_text):\n",
        "    clean_input = clean_text(user_text)\n",
        "    features = vectorizer.transform([clean_input])\n",
        "    prediction = model.predict(features)[0]\n",
        "    return encoder.inverse_transform([prediction])[0]\n",
        "\n",
        "example_inputs = [\n",
        "    'I have been feeling anxious and I cannot sleep at night',\n",
        "    'I feel very sad and hopeless',\n",
        "]\n",
        "\n",
        "for sample in example_inputs:\n",
        "    print(f'Input: {sample}')\n",
        "    print(f'Predicted intent: {predict_intent(sample)}')\n",
        "    print()\n",
    ],
})

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": sys.version.split()[0]},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

notebook_path.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"Wrote notebook to {notebook_path}")
